// Generated by rstantools.  Do not edit by hand.

/*
    dgevbhm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    dgevbhm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with dgevbhm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_dgev_bhm_COV_xi_j_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 56> locations_array__ =
  {" (found before start of program)",
  " (in 'dgev_bhm_COV_xi_j', line 24, column 2 to column 13)",
  " (in 'dgev_bhm_COV_xi_j', line 25, column 2 to column 13)",
  " (in 'dgev_bhm_COV_xi_j', line 26, column 2 to column 28)",
  " (in 'dgev_bhm_COV_xi_j', line 27, column 2 to column 34)",
  " (in 'dgev_bhm_COV_xi_j', line 28, column 2 to column 27)",
  " (in 'dgev_bhm_COV_xi_j', line 29, column 2 to column 34)",
  " (in 'dgev_bhm_COV_xi_j', line 30, column 2 to column 21)",
  " (in 'dgev_bhm_COV_xi_j', line 31, column 2 to column 36)",
  " (in 'dgev_bhm_COV_xi_j', line 34, column 2 to column 16)",
  " (in 'dgev_bhm_COV_xi_j', line 36, column 4 to column 36)",
  " (in 'dgev_bhm_COV_xi_j', line 35, column 17 to line 37, column 3)",
  " (in 'dgev_bhm_COV_xi_j', line 35, column 2 to line 37, column 3)",
  " (in 'dgev_bhm_COV_xi_j', line 40, column 2 to column 14)",
  " (in 'dgev_bhm_COV_xi_j', line 42, column 2 to column 24)",
  " (in 'dgev_bhm_COV_xi_j', line 43, column 2 to column 23)",
  " (in 'dgev_bhm_COV_xi_j', line 44, column 2 to column 32)",
  " (in 'dgev_bhm_COV_xi_j', line 45, column 2 to column 26)",
  " (in 'dgev_bhm_COV_xi_j', line 48, column 6 to column 68)",
  " (in 'dgev_bhm_COV_xi_j', line 49, column 6 to column 62)",
  " (in 'dgev_bhm_COV_xi_j', line 52, column 8 to column 54)",
  " (in 'dgev_bhm_COV_xi_j', line 53, column 8 to column 17)",
  " (in 'dgev_bhm_COV_xi_j', line 51, column 27 to line 54, column 7)",
  " (in 'dgev_bhm_COV_xi_j', line 51, column 6 to line 54, column 7)",
  " (in 'dgev_bhm_COV_xi_j', line 47, column 20 to line 55, column 5)",
  " (in 'dgev_bhm_COV_xi_j', line 47, column 4 to line 55, column 5)",
  " (in 'dgev_bhm_COV_xi_j', line 46, column 17 to line 56, column 3)",
  " (in 'dgev_bhm_COV_xi_j', line 46, column 2 to line 56, column 3)",
  " (in 'dgev_bhm_COV_xi_j', line 15, column 2 to column 17)",
  " (in 'dgev_bhm_COV_xi_j', line 16, column 2 to column 17)",
  " (in 'dgev_bhm_COV_xi_j', line 17, column 2 to column 23)",
  " (in 'dgev_bhm_COV_xi_j', line 18, column 8 to column 9)",
  " (in 'dgev_bhm_COV_xi_j', line 18, column 10 to column 11)",
  " (in 'dgev_bhm_COV_xi_j', line 18, column 2 to column 28)",
  " (in 'dgev_bhm_COV_xi_j', line 19, column 9 to column 16)",
  " (in 'dgev_bhm_COV_xi_j', line 19, column 2 to column 20)",
  " (in 'dgev_bhm_COV_xi_j', line 20, column 9 to column 10)",
  " (in 'dgev_bhm_COV_xi_j', line 20, column 2 to column 14)",
  " (in 'dgev_bhm_COV_xi_j', line 21, column 9 to column 10)",
  " (in 'dgev_bhm_COV_xi_j', line 21, column 2 to column 16)",
  " (in 'dgev_bhm_COV_xi_j', line 26, column 18 to column 19)",
  " (in 'dgev_bhm_COV_xi_j', line 27, column 28 to column 29)",
  " (in 'dgev_bhm_COV_xi_j', line 28, column 18 to column 19)",
  " (in 'dgev_bhm_COV_xi_j', line 29, column 27 to column 28)",
  " (in 'dgev_bhm_COV_xi_j', line 34, column 9 to column 10)",
  " (in 'dgev_bhm_COV_xi_j', line 3, column 4 to column 11)",
  " (in 'dgev_bhm_COV_xi_j', line 9, column 6 to column 27)",
  " (in 'dgev_bhm_COV_xi_j', line 10, column 6 to column 39)",
  " (in 'dgev_bhm_COV_xi_j', line 8, column 11 to line 11, column 5)",
  " (in 'dgev_bhm_COV_xi_j', line 5, column 6 to column 36)",
  " (in 'dgev_bhm_COV_xi_j', line 6, column 18 to column 45)",
  " (in 'dgev_bhm_COV_xi_j', line 6, column 6 to column 45)",
  " (in 'dgev_bhm_COV_xi_j', line 7, column 6 to column 63)",
  " (in 'dgev_bhm_COV_xi_j', line 4, column 26 to line 8, column 5)",
  " (in 'dgev_bhm_COV_xi_j', line 4, column 4 to line 11, column 5)",
  " (in 'dgev_bhm_COV_xi_j', line 2, column 54 to line 12, column 3)"};
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
gev_lpdf(const T0__& y, const T1__& mu, const T2__& sigma, const T3__& xi,
         std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
gev_lpdf(const T0__& y, const T1__& mu, const T2__& sigma, const T3__& xi,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ z = DUMMY_VAR__;
    current_statement__ = 54;
    if (stan::math::logical_gt(stan::math::fabs(xi), 1e-10)) {
      current_statement__ = 49;
      z = (1 + ((xi * (y - mu)) / sigma));
      current_statement__ = 51;
      if (stan::math::logical_lte(z, 0)) {
        current_statement__ = 50;
        return stan::math::negative_infinity();
      }
      current_statement__ = 52;
      return ((-stan::math::log(sigma) - ((1 + (1 / xi)) *
             stan::math::log(z))) - stan::math::pow(z, (-1 / xi)));
    } else {
      current_statement__ = 46;
      z = ((y - mu) / sigma);
      current_statement__ = 47;
      return ((-stan::math::log(sigma) - z) - stan::math::exp(-z));
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_dgev_bhm_COV_xi_j final : public model_base_crtp<model_dgev_bhm_COV_xi_j> {
private:
  int J;
  int D;
  int N_total;
  std::vector<std::vector<int>> s;
  Eigen::Matrix<double,-1,1> y_data__;
  Eigen::Matrix<double,-1,1> d_data__;
  Eigen::Matrix<double,-1,1> COV_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> d{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> COV{nullptr, 0};
public:
  ~model_dgev_bhm_COV_xi_j() {}
  model_dgev_bhm_COV_xi_j(stan::io::var_context& context__, unsigned int
                          random_seed__ = 0, std::ostream*
                          pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_dgev_bhm_COV_xi_j_namespace::model_dgev_bhm_COV_xi_j";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 28;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 28;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "D", "int",
        std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      current_statement__ = 29;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "D", D, 0);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "N_total", "int",
        std::vector<size_t>{});
      N_total = std::numeric_limits<int>::min();
      current_statement__ = 30;
      N_total = context__.vals_i("N_total")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "N_total", N_total, 0);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("s", "D", D);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("s", "J", J);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "s", "int",
        std::vector<size_t>{static_cast<size_t>(D), static_cast<size_t>(J)});
      s = std::vector<std::vector<int>>(D,
            std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> s_flat__;
        current_statement__ = 33;
        s_flat__ = context__.vals_i("s");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 33;
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            current_statement__ = 33;
            stan::model::assign(s, s_flat__[(pos__ - 1)],
              "assigning variable s", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 33;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "s", s, 0);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("y", "N_total", N_total);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N_total)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N_total,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(),
        N_total);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 35;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= N_total; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("d", "D", D);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "d", "double",
        std::vector<size_t>{static_cast<size_t>(D)});
      d_data__ = Eigen::Matrix<double,-1,1>::Constant(D,
                   std::numeric_limits<double>::quiet_NaN());
      new (&d) Eigen::Map<Eigen::Matrix<double,-1,1>>(d_data__.data(), D);
      {
        std::vector<local_scalar_t__> d_flat__;
        current_statement__ = 37;
        d_flat__ = context__.vals_r("d");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(d, d_flat__[(pos__ - 1)],
            "assigning variable d", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 38;
      stan::math::validate_non_negative_index("COV", "J", J);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "COV", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      COV_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&COV) Eigen::Map<Eigen::Matrix<double,-1,1>>(COV_data__.data(), J);
      {
        std::vector<local_scalar_t__> COV_flat__;
        current_statement__ = 39;
        COV_flat__ = context__.vals_r("COV");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 39;
          stan::model::assign(COV, COV_flat__[(pos__ - 1)],
            "assigning variable COV", stan::model::index_uni(sym1__));
          current_statement__ = 39;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 40;
      stan::math::validate_non_negative_index("sigma0", "J", J);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("xi", "J", J);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("theta", "J", J);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("eta", "J", J);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("mut", "J", J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + J + J + J + J + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_dgev_bhm_COV_xi_j";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_dgev_bhm_COV_xi_j_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mut_0 = DUMMY_VAR__;
      current_statement__ = 1;
      mut_0 = in__.template read<local_scalar_t__>();
      local_scalar_t__ mut_1 = DUMMY_VAR__;
      current_statement__ = 2;
      mut_1 = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> sigma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 3;
      sigma0 = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 J);
      Eigen::Matrix<local_scalar_t__,-1,1> xi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 4;
      xi = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(-1, 1, lp__,
             J);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      theta = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 6;
      eta = in__.template read_constrain_lub<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__,
              J);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 7;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ delta = DUMMY_VAR__;
      current_statement__ = 8;
      delta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(-0.5, 0.5, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> mut =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 12;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 10;
        stan::model::assign(mut, (mut_0 + (mut_1 *
          stan::model::rvalue(COV, "COV", stan::model::index_uni(j)))),
          "assigning variable mut", stan::model::index_uni(j));
      }
      {
        int pos = std::numeric_limits<int>::min();
        current_statement__ = 13;
        pos = 1;
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mut_0, 0, 10));
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mut_1, 0, 5));
        current_statement__ = 16;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(sigma0, (beta * 10),
                         10));
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(xi, delta, 0.1));
        current_statement__ = 27;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 25;
          for (int dd = 1; dd <= D; ++dd) {
            local_scalar_t__ mu = DUMMY_VAR__;
            current_statement__ = 18;
            mu = ((stan::model::rvalue(mut, "mut", stan::model::index_uni(j))
              *
              stan::model::rvalue(sigma0, "sigma0", stan::model::index_uni(j)))
              *
              stan::math::pow(
                (stan::model::rvalue(d, "d", stan::model::index_uni(dd)) +
                stan::model::rvalue(theta, "theta", stan::model::index_uni(j))),
                -stan::model::rvalue(eta, "eta", stan::model::index_uni(j))));
            local_scalar_t__ sigma = DUMMY_VAR__;
            current_statement__ = 19;
            sigma = (stan::model::rvalue(sigma0, "sigma0",
                       stan::model::index_uni(j))
              *
              stan::math::pow(
                (stan::model::rvalue(d, "d", stan::model::index_uni(dd)) +
                stan::model::rvalue(theta, "theta", stan::model::index_uni(j))),
                -stan::model::rvalue(eta, "eta", stan::model::index_uni(j))));
            current_statement__ = 23;
            for (int i = 1; i <=
                 stan::model::rvalue(s, "s", stan::model::index_uni(dd),
                   stan::model::index_uni(j)); ++i) {
              current_statement__ = 20;
              lp_accum__.add(gev_lpdf<false>(
                               stan::model::rvalue(y, "y",
                                 stan::model::index_uni(pos)), mu, sigma,
                               stan::model::rvalue(xi, "xi",
                                 stan::model::index_uni(j)), pstream__));
              current_statement__ = 21;
              pos = (pos + 1);
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_dgev_bhm_COV_xi_j_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mut_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mut_0 = in__.template read<local_scalar_t__>();
      double mut_1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      mut_1 = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> sigma0 =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      sigma0 = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 J);
      Eigen::Matrix<double,-1,1> xi =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      xi = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(-1, 1, lp__,
             J);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      theta = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<double,-1,1> eta =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      eta = in__.template read_constrain_lub<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__,
              J);
      double beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double delta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      delta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(-0.5, 0.5, lp__);
      Eigen::Matrix<double,-1,1> mut =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(mut_0);
      out__.write(mut_1);
      out__.write(sigma0);
      out__.write(xi);
      out__.write(theta);
      out__.write(eta);
      out__.write(beta);
      out__.write(delta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 12;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 10;
        stan::model::assign(mut, (mut_0 + (mut_1 *
          stan::model::rvalue(COV, "COV", stan::model::index_uni(j)))),
          "assigning variable mut", stan::model::index_uni(j));
      }
      if (emit_transformed_parameters__) {
        out__.write(mut);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mut_0 = DUMMY_VAR__;
      current_statement__ = 1;
      mut_0 = in__.read<local_scalar_t__>();
      out__.write(mut_0);
      local_scalar_t__ mut_1 = DUMMY_VAR__;
      current_statement__ = 2;
      mut_1 = in__.read<local_scalar_t__>();
      out__.write(mut_1);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(sigma0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable sigma0");
      out__.write_free_lb(0, sigma0);
      Eigen::Matrix<local_scalar_t__,-1,1> xi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(xi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable xi");
      out__.write_free_lub(-1, 1, xi);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable theta");
      out__.write_free_lb(0, theta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(eta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable eta");
      out__.write_free_lub(0, 1, eta);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 7;
      beta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, beta);
      local_scalar_t__ delta = DUMMY_VAR__;
      current_statement__ = 8;
      delta = in__.read<local_scalar_t__>();
      out__.write_free_lub(-0.5, 0.5, delta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mut_0", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "mut_1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma0", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "xi", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "eta", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "delta", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mut_0 = DUMMY_VAR__;
      current_statement__ = 1;
      mut_0 = context__.vals_r("mut_0")[(1 - 1)];
      out__.write(mut_0);
      local_scalar_t__ mut_1 = DUMMY_VAR__;
      current_statement__ = 2;
      mut_1 = context__.vals_r("mut_1")[(1 - 1)];
      out__.write(mut_1);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma0_flat__;
        current_statement__ = 3;
        sigma0_flat__ = context__.vals_r("sigma0");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(sigma0, sigma0_flat__[(pos__ - 1)],
            "assigning variable sigma0", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma0);
      Eigen::Matrix<local_scalar_t__,-1,1> xi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> xi_flat__;
        current_statement__ = 4;
        xi_flat__ = context__.vals_r("xi");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(xi, xi_flat__[(pos__ - 1)],
            "assigning variable xi", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(-1, 1, xi);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 5;
        theta_flat__ = context__.vals_r("theta");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, theta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 6;
        eta_flat__ = context__.vals_r("eta");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(eta, eta_flat__[(pos__ - 1)],
            "assigning variable eta", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(0, 1, eta);
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 7;
      beta = context__.vals_r("beta")[(1 - 1)];
      out__.write_free_lb(0, beta);
      local_scalar_t__ delta = DUMMY_VAR__;
      current_statement__ = 8;
      delta = context__.vals_r("delta")[(1 - 1)];
      out__.write_free_lub(-0.5, 0.5, delta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mut_0", "mut_1", "sigma0", "xi",
                "theta", "eta", "beta", "delta"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"mut"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mut_0");
    param_names__.emplace_back(std::string() + "mut_1");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "xi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "delta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "mut" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mut_0");
    param_names__.emplace_back(std::string() + "mut_1");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "xi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "delta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "mut" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mut_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mut_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mut\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mut_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mut_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mut\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((1 + 1) + J) + J) + J) + J) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (J);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((1 + 1) + J) + J) + J) + J) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (J);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_dgev_bhm_COV_xi_j_namespace::model_dgev_bhm_COV_xi_j;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_dgev_bhm_COV_xi_j_namespace::profiles__;
}
#endif
#endif
